DROP DATABASE IF EXISTS just_todo_it_db;
CREATE DATABASE just_todo_it_db;

\c just_todo_it_db;

-- DROP TABLE IF EXISTS todos CASCADE; 
-- DROP TABLE IF EXISTS users CASCADE; 
-- DROP TABLE IF EXISTS winners CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username VARCHAR NOT NULL 
);

CREATE TABLE todos (
  id VARCHAR PRIMARY KEY,
  owner VARCHAR,
  text VARCHAR NOT NULL,
  completed BOOLEAN DEFAULT FALSE
);
